-- MySQL Script generated by MySQL Workbench
-- Sat Aug 22 16:36:54 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema webboot
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webboot
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webboot` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema webboot
-- -----------------------------------------------------
USE `webboot` ;

-- -----------------------------------------------------
-- Table `webboot`.`admin_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webboot`.`admin_user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `login_name` VARCHAR(45) NOT NULL COMMENT '登录名',
  `display_name` VARCHAR(45) NOT NULL COMMENT '展示名',
  `password` VARCHAR(45) NOT NULL COMMENT '密码(密文)',
  `last_login_time` DATETIME NULL COMMENT '最后登录时间',
  `create_time` DATETIME NULL COMMENT '创建时间',
  `update_time` DATETIME NULL COMMENT '更新时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webboot`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webboot`.`permission` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `code` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webboot`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webboot`.`role` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webboot`.`admin_user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webboot`.`admin_user_role` (
  `role_id` BIGINT(20) NOT NULL,
  `admin_user_id` BIGINT(20) NOT NULL,
  INDEX `fk_admin_user_role_role_idx` (`role_id` ASC),
  INDEX `fk_admin_user_role_admin_user1_idx` (`admin_user_id` ASC),
  PRIMARY KEY (`role_id`, `admin_user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webboot`.`admin_user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webboot`.`admin_user_role` (
  `role_id` BIGINT(20) NOT NULL,
  `admin_user_id` BIGINT(20) NOT NULL,
  INDEX `fk_admin_user_role_role_idx` (`role_id` ASC),
  INDEX `fk_admin_user_role_admin_user1_idx` (`admin_user_id` ASC),
  PRIMARY KEY (`role_id`, `admin_user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webboot`.`role_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webboot`.`role_permission` (
  `role_id` BIGINT(20) NOT NULL,
  `permission_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`role_id`, `permission_id`),
  INDEX `fk_role_permission_permission1_idx` (`permission_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webboot`.`admin_user_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webboot`.`admin_user_permission` (
  `admin_user_id` BIGINT(20) NOT NULL,
  `permission_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`admin_user_id`, `permission_id`),
  INDEX `fk_admin_user_permission_permission1_idx` (`permission_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Table `webboot`.`admin_user_login_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin_user_login_log` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `login_time` DATETIME NULL COMMENT '登录时间',
  `admin_user_id` BIGINT(20) NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `admin_user_id`)  COMMENT '',
  INDEX `fk_admin_user_login_log_admin_user1_idx` (`admin_user_id` ASC)  COMMENT '',
  CONSTRAINT `fk_admin_user_login_log_admin_user1`
    FOREIGN KEY (`admin_user_id`)
    REFERENCES admin_user (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'admin用户登录表';



-- 数据初始化 增加后台主账号, admin/admin
insert into admin_user
(login_name,display_name,password,create_time,update_time)
values
  ('admin','管理员',md5('adminkey_slot'),now(),now());
